
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: twistlock-view
rules:
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings", "clusterroles", "clusterrolebindings"] # Allow Defenders to list RBAC resources
  verbs: ["list"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"] # Allow Defenders to get Deployments and ReplicaSets
  verbs: ["get"]
- apiGroups: [""] # Core API
  resources: ["namespaces", "pods"] # Allow Defenders to get Namespaces and Pods
  verbs: ["get"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: twistlock-view-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: twistlock-view
subjects:
- apiGroup:
  kind: ServiceAccount
  name: twistlock-service
  namespace: twistlock
---

---
apiVersion: v1
kind: Secret
metadata:
  name: twistlock-secrets
  namespace: twistlock
type: Opaque
data:
  service-parameter: eWduSDRDeEYvVzF3Y0x5OGM2c3Z0VDJtQStwYjBjd3RnSlcvdDZtK1N1NlplaWFOWjFHZmR0akZod2pMZ0JJRzBPNjFzbzZsN2dsdEIwZzVRSG9OSUE9PQ==
  defender-ca.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURIVENDQWdXZ0F3SUJBZ0lSQUxPSE9yaFpSOGRpR1JWUDRHV0lUZTR3RFFZSktvWklodmNOQVFFTEJRQXcKS0RFU01CQUdBMVVFQ2hNSlZIZHBjM1JzYjJOck1SSXdFQVlEVlFRREV3bFVkMmx6ZEd4dlkyc3dIaGNOTWpVdwpNVEU1TVRBME9UQXdXaGNOTWpnd01URTVNVEEwT1RBd1dqQW9NUkl3RUFZRFZRUUtFd2xVZDJsemRHeHZZMnN4CkVqQVFCZ05WQkFNVENWUjNhWE4wYkc5amF6Q0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0MKZ2dFQkFMMFdaQ1ZXdGRnU2lpRjdwV0RyS0FzVkFmTU5PNDE2dDdHY1pramZCYWVyVU1kL2x4MDV1K1cxcGlESQpsbHNCQ0lJeTRQV3E0ZDUrUTBkOXJHVWZQNVdVWExkdjljL21DWFJMa2VNUWRDVmR3M3I0dHhibG5vbEE4Q2FnClhUaldSWFkxcXpiV2dLeXFvUTl0am54QXNteGhKS28vM1hSL0JlUmYyS29raDJobG81N3d0ZmQxTVNvZy8zd3kKNlllejdsbkxJRUpiWFZONmVreGRlMkM5WEFCam42clkrZzZ4VURPVHAvYmRBanlKTlFMVENTYWhVWUxVR28yZApWMHpqS3pac0tFa2VmV0xUY3RCZVJydjhtQlZaNFNRTzlBUVk0S2lLUGZQMEJKeno0dGVlODVtNVdjOWUvd0Q0CmJ4dHlqVnRnNmVPdU5yR2N6RWNxWW5VWThkY0NBd0VBQWFOQ01FQXdEZ1lEVlIwUEFRSC9CQVFEQWdLc01BOEcKQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGRFExdTVrUjFzQUUydjUxcGcwNUxaQm4yNDI4TUEwRwpDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ29zTFNUODlVeWM3SXVoYXFhc0taWTRuM2pBeFc1N3dITnNWeUlRZnF3CnplamwyL1FIL2tBUno0YkthL2lJZ2Iwc1B4WDdFSmNBRmxtclgxbkFDaHRYRjNmNUpJcDZHeThpK1ZXOTZ3N2cKc1dWdEoxRWphUC80T1ZNNWt4eDVIL1djRkxoR1ZLYkRkaWtJZWQwZEN4ZFdOaU4yQTE5bXlrQTcrekxndC9kTAp3eStBdGZNTnRLVkRWTjBhOGtSZzBCbEdhSnZjZW8xVm5uMXZ4Tkh4ZCtYOXRqbndUU1hCRTRyYjRReUZiYnp3CnZTS2VCUEZsM2VJME03dXpFR053LzB1S2ZPT2VnaG1ibGVnZll1UnNGNHM3MUVYYWc0UlBrUm1sbUs5RkF1b2UKQnpNYkNlOXdpR1cxeVVldVIzeUcxTGV4QU53SmVibHA0cS9CZGpMYTlZVWoKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  defender-client-cert.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURPekNDQWlPZ0F3SUJBZ0lRSUs0K0pHdSt1VXc5ZUpna1AxeEV3ekFOQmdrcWhraUc5dzBCQVFzRkFEQW8KTVJJd0VBWURWUVFLRXdsVWQybHpkR3h2WTJzeEVqQVFCZ05WQkFNVENWUjNhWE4wYkc5amF6QWVGdzB5TlRBeApNVGt4TURRNU1EQmFGdzB5T0RBeE1Ua3hNRFE1TURCYU1DZ3hFakFRQmdOVkJBb1RDVlIzYVhOMGJHOWphekVTCk1CQUdBMVVFQXhNSmJHOWpZV3hvYjNOME1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0MKQVFFQW9YNVZZaUJqdWF2bDhndHBVOVB3NWlMZEVEMzMwMDNsZmhEaTJESGY5U3dqZUJLM013Y1ZYVFNENGZkcAo1NWhSNG8zWmhSOVk0aDkzbEZmTHFXSndIK1pMMEk3dDczbkV1a05ZaDd6anQ2UkFDQUVpc2tDa2tLQjFwbE1ICmNRdEhJZ21CK1NzdTVjajZMTXNCOEJXbks0VEg3Y29Sc25lcHhDS1dnUU9PaVdWSWhBcUt4MlI0MmNFcVU5ZE8KcUpUdG5vTlpFWE9JTHAvSHBScytBTnhqMFJFbU1VTEszM0xoRzMxQ1BVOE5zM29KTnNsVXpKejJTTVFqRmY1NgovbFcxTTUza3YwOEF2em0wWnNvZ3ZCdndweGRqOE1TSFBRSHFDWUIvbldRL3hCM0FRdjJpSnlZSWhLQzIxMC9JCkNEYklJT0xDMFJnNTVWODFaQzg0ekwreGpRSURBUUFCbzJFd1h6QU9CZ05WSFE4QkFmOEVCQU1DQjRBd0V3WUQKVlIwbEJBd3dDZ1lJS3dZQkJRVUhBd0l3REFZRFZSMFRBUUgvQkFJd0FEQWZCZ05WSFNNRUdEQVdnQlEwTmJ1WgpFZGJBQk5yK2RhWU5PUzJRWjl1TnZEQUpCZ1VxQkFFQ0J3UUFNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUFuCi8rdmUrWitXbytZS09SWTVWd282bzhDMzdhc2UzMGpkaDhPTGQ2ZkdKb2lja2dBOEhTYmZQeVpQR1dsTzNYV2oKQko3V0o3ekR5WTkvZXBNZkZoRVVLT241UEJPNEpRQkZlSDVxdkR4V0pQWGZUQUFQRldsK2RkNmp2ZUxIRXlVRQpnUFR6VjRqWUNjMWlJaGJ4OTl2Q1FDdkhpaW1lakZoWG1zRDNtWkxmUCtHaFE4aHlVbDhiN2xLYXlTdWN2Tkt4Cm9Ja1F2ck1pbWRNVkRyMmNSdXcxMWhLTjVoS2JzYlVmL1JxKzBHWTB6c1l1SFJZRzNnZElDcnpMeC93aG9UVnEKYmJYT21WeVV2UStScmQvR1VjZlBpY214Ui9iZjNYRXRZbTFabFlGWW9PREZHYlJUd3lKV3M0YnhCVWkzTG93cwoxT005c0xib0F4OGRTREFKKzk0RQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  defender-client-key.pem: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpQcm9jLVR5cGU6IDQsRU5DUllQVEVECkRFSy1JbmZvOiBBRVMtMjU2LUNCQyxkOGNkMTdkODUxYWQ0M2M0NzYyMmE1NTg1MWM0N2I1ZAoKWnBqUCs1cGkyTmpKRUlGNlk2cTVjUXdZMHY5YWthNUlxNDN1UUQzYUthNGsvNWtTSDRsaHliUHJOUGFhYmZYbApSQktkeGFCWnVLOUNDY1Q3UEovRHNDZDVLNC8vcGtmcWpXWjRXUWlXUFgxZTBvZWRPYnNrWGhpdXNYbnNYRjMxClUwam05QzZmK0NWK1IxRG0rUjU2eC9VeTR1d0dnbU52K1k1TWh1UkVuU0tqbjl4VXJuKzdCRzFxWjA4bEVBYTMKN1hGOHVSV0NVVTNqMmNMNmtTNy96SGNjYlVOelJPTTlaejMvalV4QnUzaW52UnlHbktuVWtPaU0vRHdqOWdORQpHVHozQk9tc2ZYUGJzaFEzbXJKMXhlLzFqTkRQUlQ1S0srZkFpSDFWMnljKzZpMTJaRTg0SmszWlR5SU1ZcWpxCjJJZDFuY2wzbnJTOVp3bldFRmVuSUVtakZCUnhCQmVpWExzTkVIb09NbmM0emNIRGtLVDJ5UEpSQ2FCY0oxZlEKWXI3ck5oZEZzOFNpMUl0QXBHZEF5cVFvMjBkRWF3WUl4eVdUZ0tpTzRGdE5hZmVyZzU2citUbUo0U1RWZVViTgpCZkRjMGUvOXcxTkMyeEdhWDJsWnZOQ3IzQ2FSY3h4aXk2Yll5MlEyTkRWTTJHcVVjNnlUZ21IVjlxL1V2bUl0Cit5ek94U1k0ZG5oWDVoRHYxOTFselNhbHR4NXhZZTFyZE1UYkRyeDdiamVvcUdxcUZzZW1LazJvdDlMMjBjM2EKYlZjd1h3UDVwWXBCTnd6RStyYnRvd1BpcWpFcDdNcHNnemRMSi95K3NSaEZUQmdZQUp5RU56eDQya3hqenBlMApxVUdLRnh6bVBrQmd2TG1pWXRhL20wVzhSbDYwNkxHRm1vMDNlM0N1NGxHRDZOK1E2dS9hNDdocDhPaHYzcWNpCm9NT0pIU3VieFQ2QXFSbE1jOFlzbHYwVVhmbHkzSUtaY1pka2didE1rU1ZaRHpIZ1Zjdnd6a3dESnZNRzhYdzIKWElKVnJBUGRBSUdjVnBYWklGdFRPRDA5RFpqMWNXUTZZU1drcE9qamUvbWJNODh1eWRNeU9QcTJOMFhsSzNPbwpGeE8zcTY2Z0R4Tm4rZ3M1NTdZcEZSbm8zK0Zuc0cyN3BjT25paEx5NC9HQ0xXSkxBOGM4bWQvS0kxMTFyUGFmCmNybUFndlF3dGlXa010QkM3aFVNaWxyUWUwV2g2Ukh2MnZsTTRWT01wWkRld1NqcjdYVCtzZWdMek43aGVNaFgKbDVOemJSdjd5Mkk2KzJsZTgvKzh6RjdWU0ZYbVMrdWlTN3pPck5jWXdxTzc5ZnlqQ1VsM2JwODg2U0xWYjlESQppWjgxMFNHWG84Vzh4YlFZQUVmZjQvNG9lYVJRL3RrT0VYL3dBc2psWWEwWlphUUp5eU9zVHBlT1dNZHhNMWhaCnF5MEF6WFdORVNuMmh6RzVUUkpuNGJNZHJ4OFVpRXd1aElTQ2UxenpweE0vaVowejdVaklvbnBJZDNFYXpycGQKYTA5OEl5VGZLdTZ2TGRFV0ZxTDltbUVnVksxR1hWMXowYlV0bndwVkNUVU85Wm1uTDFQMlZtcTB0MjdhU3hzZQozQm9tRC8vMHNFbG5zT0JqQ2FibHpheTVmNjBCT29INmdlY2tqcDd3RkM1UnFOaldkUUxsN2Ivc0ZrTmw1YlFmCktKMlpCcTkvb1JkTndqdzRZcFVLTGg3Z3ZGdDFTQVpSZG9OVmh4VkJJcVlsckRIVVFFbGZBRjRQRFZibmRWSS8KOUZ6MGd0dCsvVXN4ampwa2dBZ0JkSGtvSnUzc2graTY0bTIrYndDTFJJWWlpMHpXanlBSk80VW5PWEZQSWkyUQpTNDA0ZjVCbmRpUE9kdzMyWGNYVDJvTCtFTXd0cnNaZENuUmYvZ3h4UUNEbnNBZmJ2ZmJ4UmlYbHp1ekhyMFlIClo0R09ab2VCbzlzcVVPSDZOcGx6Q090MnVGajU1M2dMOHBpMko2bjZmNXBmRWZaZklsMmVPdDFFbXJ4RitvTVUKb080ck1pRVRNL3o3aE9FL3hSNjg0dWw5UndsQzJKdVdDV3NZNTdCL3I0M1hid1ZoY01NR3FLS0U3ekc4S3RjRAotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
  admission-cert.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURURENDQWpTZ0F3SUJBZ0lSQUt1YUpkemZWdldqZUoyRmk4aFhnZkl3RFFZSktvWklodmNOQVFFTEJRQXcKS0RFU01CQUdBMVVFQ2hNSlZIZHBjM1JzYjJOck1SSXdFQVlEVlFRREV3bFVkMmx6ZEd4dlkyc3dIaGNOTWpVdwpNVEl3TVRZeU1EQXdXaGNOTWpnd01USXdNVFl5TURBd1dqQVVNUkl3RUFZRFZRUUtFd2xVZDJsemRHeHZZMnN3CmdnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURLL2FUUm8xM0lGYWZ4dXp6NjUxckYKbWF3cHRha0hQWm5LUVB2VE9VYUpsMDk0Y1N4NHVra3Q5a3J5MElTT2hlVis3SnM2UXBvOGJVaElSSTB0WDM4aQpjU3k1NHZPTkpBS0IzRzhOMlYrTXBMaEw5WXBPZFBZdkhuUkRCRnpoWVB3Q1RtYnF3Q3BJT0hPUC9MSElJNG0yClpFeTUrdTJuc0EvaC90WTJNVGN5dXhtY09DVHVNNTZVVkVwUlFWSTllYUljaG9HNkRIR3g4NkxGbXZSOSs2VzUKcVlDdUptNy9kbjgvTTBJWHIxZXFiZ1RIaDRsYUlucm1TMUxSRzdJV0RrTTFLNzJsSlNVV2xJZ0N2NlhiNW5QRApHOGo2UmhQODBJY2JHYVM5Z0JpK21rc2t3aVh0VHFXN1drcEtkWWY0TW9qamFyYzM1N1ArS2UwTjRFLzlFczRSCkFnTUJBQUdqZ1lRd2dZRXdEZ1lEVlIwUEFRSC9CQVFEQWdPb01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUMKQmdnckJnRUZCUWNEQVRBTUJnTlZIUk1CQWY4RUFqQUFNQjhHQTFVZEl3UVlNQmFBRkRRMXU1a1Ixc0FFMnY1MQpwZzA1TFpCbjI0MjhNQ0VHQTFVZEVRUWFNQmlDRm1SbFptVnVaR1Z5TG5SM2FYTjBiRzlqYXk1emRtTXdEUVlKCktvWklodmNOQVFFTEJRQURnZ0VCQUZSZXgzY25EYzloVjFHNXprd0hlV292S2o1L3BreHkwb2t0WlJmUGprMFUKUy9uaHFvTWhiMFFnb2QwZ3BlUHdWUjJOdzdPdXB2Z3lsSk5Zc25wVlQ2TXRKSk1oVU53dFhXMDFIVHAwOUsxSApMaVJzOG5YRndlSldPaElNbmUrd2ZNMERqRTVLbERVcXhQcmR4d1FRRXdtaEoyT0lKWGRwRW51Y0tQVWZNSFMyCkxaUWNXVUJoT0FYV0pDMUIwK3JxTjlKR0hsN3ZVWHNqemdRaHhFdll0SVdReEhJRDdnWWtZeXZ6cEcwa05xUGMKSGR3N1kwT3dVa2RIb1J2SWJhVWFFMndkam5veFJnQmhwZVU3YUNadGZOTHdLYlZ2dC81a1o4ODR6RFlyTmcwTQpKN0pUMTZ6aU1aRkdpTGxSM0Irb2pnQ0c3NElJQTdDUHJKc2hvQzZ3NzlVPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  admission-key.pem: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpQcm9jLVR5cGU6IDQsRU5DUllQVEVECkRFSy1JbmZvOiBBRVMtMjU2LUNCQywwMTI5YmViM2QxMzI0MmFkZGFiOGYwMjM5ZGNkNjU3ZAoKdWtYVVJJZldUYUNDQ09BaTE1bnRMY29jbGVZeXdYc0NWSjAveDYwK2dOVzhKNUZIUXlLMloxeTgyUEplR1J6ZApuamNSQnk2UEpJMDFyaktEQUN6MExEZm5WdFM5cVJMcmo4Q0p2NUNRc09kemdBc2UxUWt4aVBIOHR2QXZydDZpClpSTCtTbmwzcVVJQTVoeXVTL0xXQmRUSHZKVVYya1pJZ0VDSFh4ZklYNEVTcW80V2lIZGJ3ZUs2QzcwQmNOY28KWVlPdjMwSnBQVk1sNXhoUjZEcWVicEo1a3NzeTZib0ovVnhNaEtKTkxRRTA4K2xKMDFtbWFmbGVDdGMzbkpjLworTkQ1T2h0SDFPQVdzRlpIWWJoSHA0bDhOY3EyWGJKK3lXQ1QvNGNKSUxRWDJaUXI4cVFENTJGbnM4MENLQXlYCkpFcXRFU0JQREFmajY4Y0NVV09UN3dWYlVEM0IrZ1BVMSswR0xvSTlVUnNzbldKdWtpNU84N1lzSHJHQTk4TEQKNWw3S0FjRlpPYmJKbHNGc01CQkRkK1N5TGozNVpWa0liWjdoR0VYajJocmEvblFFKzI5SS9UdFJKamxvZ0h4cgpVeHdPZFlnNkRPVitwa0EwL1lMMzl0QTYrL2k3YnRueU5DZzdSNzJEZmJWdWl2d3VpVDBmWFRPL2pDUVEzQmM1Cm93c095cmtXdDRzbmlYcStmN3g1bkYvQUhnQlBESlZhLzlMem9ydmZ0Um9VZmdGTWNaVWZrK3VIVHNUZ1RqVlUKNThhMzV3TjQ3Z2phMGpsN0tqalBrSXNSNDZrbG9IM21sZEw4eHFHVStIRmU0cnJYWGZuY2QrU1Y5U04yeklBNwpHQ0JJVHQ3d1lDZS9CMXg3ZHhYMzc0eElpS1o3bTdjM3NiTU1CYXUrNVJEbHFtVHBLbTA2TDJVSUJqaXBhY3QwCm14NE0yUi9JTGUwa1A4ZXBxWDEwV21GKytvbUxSODZ0K3RZSUd0YXlPWTRjR1A0ZTZIaHpxZHZWZmdHb1ZWY3AKQTZPMnBnYmg5aUdlK3VieHhJSHRDTlZoaTV5QWlYeGEvK3R0TU9MWU8vVTBQbHl0QjQ3aXFvdWwzUUZ2WU9NbgpXR0d0ZTkrM2RtZis0emJGeVJ4QmFYekdZNTZYSW1OQUZTbWgrT3FWUTRTSnlIUnVnYUNpMXdKczFVZ3d2NkJ4Cm02dzU3TDhTSFNRZENUZGJucTVFc0huNXhhUkt0dDFxaElOQkpUZTNKNjFXMDBZZWJxUURvRXpVY0NGUkVONDIKVHZuOTMxTTA2NTZ4WjhLYlZKTUNoZ3RSeDd4Q3BSYkVzVTA1M25CdWV3TUFhUWJoa0RHN3FXckZGZUJMamp2VgpDVDdMMDlBUWxoSno4aEZqUG82RXRVMGNGTUZGQjdHVWtZcDJqV2d5TDVFOFV1aHRTQXpjSFRyVnM2MFBkMTE1Cm05dURjZWVPelQ1dGE0YmlQTUpPeDdDejRxS1JXQTE2S2J2dkJNTXRJNkUzZnMvaXc4OHU2RG5qRUN6T2dxSGEKeE0rUWJWdHh6LzllSlFqTHVRcnFlQ05JSkE5RlVwbXhQYTN1b0FKUWtGVWcvQ0lwaFp5aE1TM2dNMnZ6SENvVQo2MFoya1FoZm5hdHV4NFhRM1VuSnkvZmQwTHBocS9CSTVWUklRQ0VITEtZbkxyNll4Yy9odGE1ejhQQVNxNERwCjN2Qy9aZUNybnB6aEYzMWxjbk4xcXgvK3c0WEFQVnN3R3lyd3NyWnE1M0V0ZWZMUkYxeStCaTlLeVVlZGozQ2EKUEwzNlZwUjB6N0xnUEl6SzQrcnpMWTh3L1ZxODlCeXM5L241bHozQzVXTnNVU3J5dkwwMDNISUpWd1MzUXpoOApRb3FYL2x4TDY4VVZoOE5BWTRiVlhSL054NlIrSVAzT3hqczU1SDdCa0w3bXNOVVYzZnpYY0sxUHQ1K3RMZzVPCjJMWTVhb2tjUE8vZitQek13cThQa2I3cEhwcUFnSGVaUHZZUjcvZzdoMGhjNzhlbFk3OWl1TDBna29zWitvOUsKUTlRV0tVd29rZHkydUZlSjVYSFR5eEQ3OWFDamZKV0V3Rm0yVDlZa1kwL0dkY3d6S1NMbGxkSGVTaGdOalRIMwotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=

---
apiVersion: v1
kind: ServiceAccount # Service Account is used for managing security context constraints policies in Openshift (SCC)
metadata:
  name: twistlock-service
  namespace: twistlock
secrets:
- name: twistlock-secrets
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: twistlock-defender-ds
  namespace: twistlock
spec:
  selector:
    matchLabels:
      app: twistlock-defender
  template:
    metadata:
      annotations:
        container.apparmor.security.beta.kubernetes.io/twistlock-defender: unconfined
      labels:
        app: twistlock-defender
    spec:
      serviceAccountName: twistlock-service
      restartPolicy: Always
      containers:
      - name: twistlock-defender
        image: registry-auth.twistlock.com/tw_fyg0eofyz4izyflykqljbyk6jbou9m0n/twistlock/defender:defender_33_03_138
        volumeMounts:
        - name: data-folder
          mountPath: "/var/lib/twistlock"
        - name: certificates # Setting the certificates mount after data-folder since it is nested and was overridden in CRI based GKE cluster
          mountPath: "/var/lib/twistlock/certificates"
        - name: docker-sock-folder
          mountPath: "/var/run"
        - name: passwd
          mountPath: "/etc/passwd"
          readOnly: true
        - name: syslog-socket
          mountPath: "/dev/log"
        - name: cri-data
          mountPath: /var/lib/containerd
        - name: cri-rke2-data
          mountPath: /var/lib/rancher/rke2/agent/containerd
        - name: runc-proxy-sock-folder
          mountPath: "/run"
        env:
        - name: WS_ADDRESS
          value: wss://us-east1.cloud.twistlock.com:443
        - name: DEFENDER_TYPE
          value: cri
        - name: LOG_PROD
          value: "true"
        - name: SYSTEMD_ENABLED
          value: "false"
        - name: DOCKER_CLIENT_ADDRESS
          value: "/var/run/docker.sock"
        - name: DEFENDER_CLUSTER_ID
          value: "fcc12674-ec47-ba89-99db-f47571b8ac51"
        - name: DEFENDER_CLUSTER_NAME_RESOLVING_METHOD
          value: "default"
        - name: DEFENDER_CLUSTER
          value: ""
        - name: MONITOR_SERVICE_ACCOUNTS
          value: "true"
        - name: MONITOR_ISTIO
          value: "false"
        - name: COLLECT_POD_LABELS
          value: "true"
        - name: INSTALL_BUNDLE
          value: "eyJzZWNyZXRzIjp7fSwiZ2xvYmFsUHJveHlPcHQiOnsiaHR0cFByb3h5IjoiIiwibm9Qcm94eSI6IiIsImNhIjoiIiwidXNlciI6IiIsInBhc3N3b3JkIjp7ImVuY3J5cHRlZCI6IiJ9fSwiY3VzdG9tZXJJRCI6InVzLTEtMTEzMDY0NzcyIiwiYXBpS2V5IjoiNk5pdVlZbm05V2FqanRwNGZmU3dUTzZGRE9la1ViTHg0RTRYWWQ5dzhmUDZ5alFzMDFEYk9qTHN3Q3RlMUVPdWJkZWVrYnlFOWpacUJtcGpaTEJPTUE9PSIsIm1pY3Jvc2VnQ29tcGF0aWJsZSI6ZmFsc2V9"
        - name: HOST_CUSTOM_COMPLIANCE_ENABLED
          value: "false"
        - name: CLOUD_HOSTNAME_ENABLED
          value: "false"
        - name: FIPS_ENABLED
          value: "false"
        securityContext:
          readOnlyRootFilesystem: true
          privileged: false
          capabilities:
            add:
            - NET_ADMIN  # Required for process monitoring
            - NET_RAW    # Required for iptables (CNNF, runtime DNS, WAAS). See: https://bugzilla.redhat.com/show_bug.cgi?id=1895032
            - SYS_ADMIN  # Required for filesystem monitoring
            - SYS_PTRACE # Required for local audit monitoring
            - SYS_CHROOT # Required for changing mount namespace using setns
            - MKNOD      # A capability to create special files using mknod(2), used by docker-less registry scanning
            - SETFCAP    # A capability to set file capabilities, used by docker-less registry scanning
            - IPC_LOCK   # Required for perf events monitoring, allowing to ignore memory lock limits
        resources: # See: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#how-pods-with-resource-requests-are-scheduled
          limits:
            memory: "512Mi"
            cpu: "900m"
          requests:
            cpu: "256m"
      volumes:
      - name: certificates
        secret:
          secretName: twistlock-secrets
          defaultMode: 256
      - name: syslog-socket
        hostPath:
          path: "/dev/log"
      - name: data-folder
        hostPath:
          path: "/var/lib/twistlock"
      - name: passwd
        hostPath:
          path: "/etc/passwd"
      - name: docker-sock-folder
        hostPath:
          path: "/var/run"
      - name: cri-data
        hostPath:
          path: /var/lib/containerd
      - name: cri-rke2-data
        hostPath:
          path: /var/lib/rancher/rke2/agent/containerd
      - name: runc-proxy-sock-folder
        hostPath:
          path: "/run"
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
---
apiVersion: v1
kind: Service # Expose the Defender as admission controller. Remark: by default, Defender will not listen on the service port
metadata:
  name: defender
  namespace: twistlock
  labels:
    app: twistlock-defender
spec:
  ports:
  - port: 443
    targetPort: 9998
  selector:
    app: twistlock-defender